import React from 'react'
import { Header, Modal, List } from 'semantic-ui-react'

const Help = ({ trigger }) => (
    <Modal trigger={trigger} dimmer='inverted'>
        <Modal.Header>Help</Modal.Header>
        <Modal.Content>
            <Modal.Description>
                <Header>What is this?</Header>
                <p>
                    This is an interactive map browser for networks clustered with <a href='http://www.mapequation.org/code.html'>Infomap</a>.<br />
                    Think of it kind of like <a href='http://maps.google.com'>Google Maps</a> for hierarchical networks.
                </p>
                <List>
                    <List.Item>
                        <List.Header>Requirements</List.Header>
                        <List.Description>
                            Extensive testing has only been done with recent versions of Chrome and Safari, but Firefox should also work.
                            This application is graphics heavy. Older computers, especially laptops with integrated GPUs will struggle to
                            keep a high frame rate.
                        </List.Description>
                    </List.Item>
                    <List.Item>
                        <List.Header>Limitations</List.Header>
                        <List.Description>
                            At the moment, only the 20 highest ranked nodes are visible per module.
                        </List.Description>
                    </List.Item>
                </List>
                <Header>Loading data</Header>
                <List ordered>
                    <List.Item>
                        <List.Header>Cluster your data with <a href='http://www.mapequation.org/code.html'>Infomap</a>.</List.Header>
                        <List.Description>
                            Use one of the supported output formats (only <tt>ftree</tt> is supported for now).<br />
                            Consider using the <tt>directed</tt> option if it suits your data.
                        </List.Description>
                    </List.Item>
                    <List.Item>
                        <List.Header>Click the <cite>Load data</cite> button on the start screen and select the file generated by Infomap.</List.Header>
                        <List.Description>
                            No data will be uploaded anywhere, everything happens locally in your browser.<br />
                            Keep in mind that there is a limit on how large files you can use. Typically sizes in the tens of megabytes will work fine.
                        </List.Description>
                    </List.Item>
                    <List.Item>
                        <List.Header>Click <cite>Show menu</cite> in the top right corner to reveal the menu.</List.Header>
                        <List.Description>
                            The menu allows you to search and display statistics for nodes and modules.
                        </List.Description>
                    </List.Item>
                </List>
                <Header>Navigation</Header>
                <List>
                    <List.Item>
                        <List.Icon name='zoom' />
                        <List.Content>
                            <List.Header>Navigate by scrolling in and out, either with your scroll wheel or two finger swiping up and down on your trackpad.</List.Header>
                            <List.Description>
                                Don't use the pinch-to-zoom gesture if you have a trackpad as this will zoom the entire page.<br />
                                When a module is zoomed in far enough, the contained network will be revealed.
                            </List.Description>
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Icon name='move' />
                        <List.Content>
                            <List.Header>Pan by click and drag.</List.Header>
                            <List.Description>
                                Click and drag anywhere where there isn't a module or node.
                            </List.Description>
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Icon name='grab' />
                        <List.Content>
                            <List.Header>The physics simulation can be manipulated by dragging modules and nodes around.</List.Header>
                            <List.Description>
                                This only works for one layer at a time, only modules which hasn't its contained network revealed can be moved.
                            </List.Description>
                        </List.Content>
                    </List.Item>
                    <List.Item>
                        <List.Icon name='area graph' />
                        <List.Content>
                            <List.Header>Select a node or module by clicking on it.</List.Header>
                            <List.Description>
                                Information about the currently selected node or module is shown in the sidebar menu under <cite>Selected node</cite>.
                            </List.Description>
                        </List.Content>
                    </List.Item>
                </List>
            </Modal.Description>
        </Modal.Content>
    </Modal>
);

export default Help
